services:
  r_env:
    # Use the same image as in your devcontainer.json
    image: docker.io/wuzicangjie/my-r-env:latest
    
    # Sets the container name for easy identification
    container_name: r-env-vscode
    
    # Run as non-root user
    user: "1000:1000"
    
    # Defines the working directory inside the container
    working_dir: /home/wuzi/project
    
    # Keep container running for dev containers
    command: sleep infinity
    
    # Mounts the current local directory and the renv cache
    volumes:
      # Mounts the project folder to the workspace directory
      - .:/home/wuzi/project:cached
      
      # Mounts the renv cache for package persistence
      - ~/.cache/R/renv:/renv/cache
      
      # Mounts the Docker socket to enable Docker-from-Docker
      # This is the standard method to achieve the "docker-from-docker" feature
      - /var/run/docker.sock:/var/run/docker.sock

    # Sets environment variables inside the container
    environment:
      # Sets the renv cache path, same as in your devcontainer.json
      - RENV_PATHS_CACHE=/renv/cache


networks:
  default:
    driver: bridge