version: '3.8'

services:
  r_env:
    # Use the same image as in your devcontainer.json
    image: docker.io/wuzicangjie/my-r-env:latest
    
    # Sets the container name for easy identification
    container_name: r-env-vscode
    
    # Run as non-root user
    user: "1000:1000"
    
    # Defines the working directory inside the container
    working_dir: /workspaces/workspace
    
    # Mounts the current local directory and the renv cache
    volumes:
      # Mounts the project folder to the workspace directory
      - .:/workspaces/workspace:cached
      
      # Mounts the renv cache for package persistence
      - ~/.cache/R/renv:/renv/cache
      
      # Mounts the Docker socket to enable Docker-from-Docker
      # This is the standard method to achieve the "docker-from-docker" feature
      - /var/run/docker.sock:/var/run/docker.sock

    # Sets environment variables inside the container
    environment:
      # Sets the renv cache path, same as in your devcontainer.json
      - RENV_PATHS_CACHE=/renv/cache
      
    # Keeps the container running
    # You can use "sleep infinity" for Linux/macOS or a different command if needed
    command: tail -f /dev/null

networks:
  default:
    driver: bridge